slurmstepd: info: Setting TMPDIR to /scratch/163749. Previous errors about TMPDIR can be discarded

(Ray_tune.py:371498): Gdk-CRITICAL **: 13:28:20.327: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
2022-05-16 13:28:30,360	WARNING function_runner.py:599 -- Function checkpointing is disabled. This may result in unexpected behavior when using checkpointing features or certain schedulers. To enable, set the train function arguments to be `func(config, checkpoint_dir=None)`.
2022-05-16 13:28:30,604	INFO trial_runner.py:803 -- starting train_graphs_4ffa3cbe
2022-05-16 13:28:35,258	INFO trial_runner.py:803 -- starting train_graphs_52d25e6c
2022-05-16 13:28:35,294	INFO trial_runner.py:803 -- starting train_graphs_52d7d2a2
2022-05-16 13:28:35,320	INFO trial_runner.py:803 -- starting train_graphs_52dbc524
2022-05-16 13:28:35,344	INFO trial_runner.py:803 -- starting train_graphs_52df61a2
2022-05-16 13:28:35,361	INFO trial_runner.py:803 -- starting train_graphs_52e21d3e
2022-05-16 13:28:35,401	INFO trial_runner.py:803 -- starting train_graphs_52e81770
2022-05-16 13:28:35,435	INFO trial_runner.py:803 -- starting train_graphs_52ed544c
2022-05-16 13:28:35,453	INFO trial_runner.py:803 -- starting train_graphs_52f0212c
2022-05-16 13:28:35,486	INFO trial_runner.py:803 -- starting train_graphs_52f52a00
2022-05-16 13:28:35,511	INFO trial_runner.py:803 -- starting train_graphs_52f8ad74
2022-05-16 13:28:35,541	INFO trial_runner.py:803 -- starting train_graphs_52fd1c38
2022-05-16 13:28:35,567	INFO trial_runner.py:803 -- starting train_graphs_53012918
2022-05-16 13:28:35,616	INFO trial_runner.py:803 -- starting train_graphs_5308d442
2022-05-16 13:28:35,638	INFO trial_runner.py:803 -- starting train_graphs_530c3d4e
2022-05-16 13:28:35,661	INFO trial_runner.py:803 -- starting train_graphs_530fb3ca
[2m[36m(train_graphs pid=374390)[0m 2022-05-16 13:28:57,333	ERROR function_runner.py:281 -- Runner Thread raised error.
[2m[36m(train_graphs pid=374390)[0m Traceback (most recent call last):
[2m[36m(train_graphs pid=374390)[0m   File "/home/uvi/ei/mfp/.local/lib/python3.7/site-packages/ray/tune/function_runner.py", line 272, in run
[2m[36m(train_graphs pid=374390)[0m     self._entrypoint()
[2m[36m(train_graphs pid=374390)[0m   File "/home/uvi/ei/mfp/.local/lib/python3.7/site-packages/ray/tune/function_runner.py", line 351, in entrypoint
[2m[36m(train_graphs pid=374390)[0m     self._status_reporter.get_checkpoint(),
[2m[36m(train_graphs pid=374390)[0m   File "/home/uvi/ei/mfp/.local/lib/python3.7/site-packages/ray/util/tracing/tracing_helper.py", line 462, in _resume_span
[2m[36m(train_graphs pid=374390)[0m     return method(self, *_args, **_kwargs)
[2m[36m(train_graphs pid=374390)[0m   File "/home/uvi/ei/mfp/.local/lib/python3.7/site-packages/ray/tune/function_runner.py", line 640, in _trainable_func
[2m[36m(train_graphs pid=374390)[0m     output = fn()
[2m[36m(train_graphs pid=374390)[0m   File "Ray_tune.py", line 274, in train_graphs
[2m[36m(train_graphs pid=374390)[0m     if(i!=0 and i%int(config["hold_gradient"])==0):
[2m[36m(train_graphs pid=374390)[0m ZeroDivisionError: integer division or modulo by zero
[2m[36m(train_graphs pid=374390)[0m Exception in thread Thread-3:
[2m[36m(train_graphs pid=374390)[0m Traceback (most recent call last):
[2m[36m(train_graphs pid=374390)[0m   File "/mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
[2m[36m(train_graphs pid=374390)[0m     self.run()
[2m[36m(train_graphs pid=374390)[0m   File "/home/uvi/ei/mfp/.local/lib/python3.7/site-packages/ray/tune/function_runner.py", line 298, in run
[2m[36m(train_graphs pid=374390)[0m     raise e
[2m[36m(train_graphs pid=374390)[0m   File "/home/uvi/ei/mfp/.local/lib/python3.7/site-packages/ray/tune/function_runner.py", line 272, in run
[2m[36m(train_graphs pid=374390)[0m     self._entrypoint()
[2m[36m(train_graphs pid=374390)[0m   File "/home/uvi/ei/mfp/.local/lib/python3.7/site-packages/ray/tune/function_runner.py", line 351, in entrypoint
[2m[36m(train_graphs pid=374390)[0m     self._status_reporter.get_checkpoint(),
[2m[36m(train_graphs pid=374390)[0m   File "/home/uvi/ei/mfp/.local/lib/python3.7/site-packages/ray/util/tracing/tracing_helper.py", line 462, in _resume_span
[2m[36m(train_graphs pid=374390)[0m     return method(self, *_args, **_kwargs)
[2m[36m(train_graphs pid=374390)[0m   File "/home/uvi/ei/mfp/.local/lib/python3.7/site-packages/ray/tune/function_runner.py", line 640, in _trainable_func
[2m[36m(train_graphs pid=374390)[0m     output = fn()
[2m[36m(train_graphs pid=374390)[0m   File "Ray_tune.py", line 274, in train_graphs
[2m[36m(train_graphs pid=374390)[0m     if(i!=0 and i%int(config["hold_gradient"])==0):
[2m[36m(train_graphs pid=374390)[0m ZeroDivisionError: integer division or modulo by zero
[2m[36m(train_graphs pid=374390)[0m 
2022-05-16 13:28:57,891	ERROR trial_runner.py:876 -- Trial train_graphs_52e21d3e: Error processing event.
NoneType: None
2022-05-16 13:28:58,714	INFO trial_runner.py:803 -- starting train_graphs_55cb3972
[2m[36m(train_graphs pid=374968)[0m 2022-05-16 13:29:20,778	ERROR function_runner.py:281 -- Runner Thread raised error.
[2m[36m(train_graphs pid=374968)[0m Traceback (most recent call last):
[2m[36m(train_graphs pid=374968)[0m   File "/home/uvi/ei/mfp/.local/lib/python3.7/site-packages/ray/tune/function_runner.py", line 272, in run
[2m[36m(train_graphs pid=374968)[0m     self._entrypoint()
[2m[36m(train_graphs pid=374968)[0m   File "/home/uvi/ei/mfp/.local/lib/python3.7/site-packages/ray/tune/function_runner.py", line 351, in entrypoint
[2m[36m(train_graphs pid=374968)[0m     self._status_reporter.get_checkpoint(),
[2m[36m(train_graphs pid=374968)[0m   File "/home/uvi/ei/mfp/.local/lib/python3.7/site-packages/ray/util/tracing/tracing_helper.py", line 462, in _resume_span
[2m[36m(train_graphs pid=374968)[0m     return method(self, *_args, **_kwargs)
[2m[36m(train_graphs pid=374968)[0m   File "/home/uvi/ei/mfp/.local/lib/python3.7/site-packages/ray/tune/function_runner.py", line 640, in _trainable_func
[2m[36m(train_graphs pid=374968)[0m     output = fn()
[2m[36m(train_graphs pid=374968)[0m   File "Ray_tune.py", line 274, in train_graphs
[2m[36m(train_graphs pid=374968)[0m     if(i!=0 and i%int(config["hold_gradient"])==0):
[2m[36m(train_graphs pid=374968)[0m ZeroDivisionError: integer division or modulo by zero
[2m[36m(train_graphs pid=374968)[0m Exception in thread Thread-3:
[2m[36m(train_graphs pid=374968)[0m Traceback (most recent call last):
[2m[36m(train_graphs pid=374968)[0m   File "/mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
[2m[36m(train_graphs pid=374968)[0m     self.run()
[2m[36m(train_graphs pid=374968)[0m   File "/home/uvi/ei/mfp/.local/lib/python3.7/site-packages/ray/tune/function_runner.py", line 298, in run
[2m[36m(train_graphs pid=374968)[0m     raise e
[2m[36m(train_graphs pid=374968)[0m   File "/home/uvi/ei/mfp/.local/lib/python3.7/site-packages/ray/tune/function_runner.py", line 272, in run
[2m[36m(train_graphs pid=374968)[0m     self._entrypoint()
[2m[36m(train_graphs pid=374968)[0m   File "/home/uvi/ei/mfp/.local/lib/python3.7/site-packages/ray/tune/function_runner.py", line 351, in entrypoint
[2m[36m(train_graphs pid=374968)[0m     self._status_reporter.get_checkpoint(),
[2m[36m(train_graphs pid=374968)[0m   File "/home/uvi/ei/mfp/.local/lib/python3.7/site-packages/ray/util/tracing/tracing_helper.py", line 462, in _resume_span
[2m[36m(train_graphs pid=374968)[0m     return method(self, *_args, **_kwargs)
[2m[36m(train_graphs pid=374968)[0m   File "/home/uvi/ei/mfp/.local/lib/python3.7/site-packages/ray/tune/function_runner.py", line 640, in _trainable_func
[2m[36m(train_graphs pid=374968)[0m     output = fn()
[2m[36m(train_graphs pid=374968)[0m   File "Ray_tune.py", line 274, in train_graphs
[2m[36m(train_graphs pid=374968)[0m     if(i!=0 and i%int(config["hold_gradient"])==0):
[2m[36m(train_graphs pid=374968)[0m ZeroDivisionError: integer division or modulo by zero
[2m[36m(train_graphs pid=374968)[0m 
2022-05-16 13:29:21,487	ERROR trial_runner.py:876 -- Trial train_graphs_55cb3972: Error processing event.
NoneType: None
2022-05-16 13:29:21,716	INFO trial_runner.py:803 -- starting train_graphs_60d2894c
slurmstepd: error: *** JOB 163749 ON ilk-128 CANCELLED AT 2022-05-16T13:29:22 DUE TO TIME LIMIT ***
